In [ ]:
# num_bins = 7  => 0.82753
# num_bins = 9  => 0.82717

In [56]:
import numpy as np
import pandas as pd 
from sklearn.naive_bayes import MultinomialNB
import csv

In [37]:
train_images = pd.read_csv('data/train.csv').to_numpy()
test_images = pd.read_csv('data/test.csv').to_numpy()

In [15]:
print(train_images)

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [7 0 0 ... 0 0 0]
 [6 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]]


In [38]:
train_labels = train_images[:, 0]
train_images = train_images[:, 1:]

In [39]:
print(train_labels)
print(train_images)

[1 0 1 ... 7 6 9]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [40]:
def values_to_bins(x, bins): 
    x = np.digitize(x, bins)    
    return x - 1

In [65]:
num_bins = 7
bins = np.linspace(0, 255, num=num_bins)  

In [66]:
bins

array([  0.   ,  31.875,  63.75 ,  95.625, 127.5  , 159.375, 191.25 ,
       223.125, 255.   ])

In [67]:
x_train = values_to_bins(train_images, bins) 
x_test = values_to_bins(test_images, bins)  

In [68]:
clf = MultinomialNB()
clf.fit(x_train, train_labels)
predicted_labels = clf.predict(x_test)

In [70]:
file = open('submission.csv', 'w')
writer = csv.writer(file)

writer.writerow(["ImageId","Label"])
for i in range(len(predicted_labels)):
    writer.writerow([i+1, predicted_labels[i]])

file.close()